services:
  app:
    image: elixir/hiverec
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: localhost
      PHX_PORT: 4000
      PHX_SCHEME: http
      PORT: 4000
  postgres:
    image: postgres
    volumes:
      - /var/lib/postgresql_phx_hiverec_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
